# Generated by Django 2.2.6 on 2019-11-01 13:04

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menus.Menu')),
            ],
            options={
                'abstract': False,
            },
            bases=('menus.menu',),
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menus.Menu')),
            ],
            options={
                'abstract': False,
            },
            bases=('menus.menu',),
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='page',
        ),
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menus.MenuItem')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_menu_items', to='menus.SubMenu')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('menus.menuitem',),
        ),
        migrations.CreateModel(
            name='MainMenuItem',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menus.MenuItem')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_menu_items', to='menus.MainMenu')),
                ('submenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menus.SubMenu')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('menus.menuitem',),
        ),
    ]
