# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 16:51
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20161208_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('doc_with_preview', wagtail.wagtailcore.blocks.StructBlock([(b'preview', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'doc', wagtail.wagtaildocs.blocks.DocumentChooserBlock())])), ('doc_with_preview_row', wagtail.wagtailcore.blocks.StructBlock([(b'first_doc', wagtail.wagtailcore.blocks.StructBlock([(b'preview', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'doc', wagtail.wagtaildocs.blocks.DocumentChooserBlock())])), (b'second_doc', wagtail.wagtailcore.blocks.StructBlock([(b'preview', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'doc', wagtail.wagtaildocs.blocks.DocumentChooserBlock())]))])), ('find_us', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=True)), (b'street', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=True)), (b'postcode', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=True)), (b'city', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=True)), (b'map_long', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=True)), (b'map_lat', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=True)), (b'map_zoom_level', wagtail.wagtailcore.blocks.CharBlock(default=14, max_length=3, required=True)), (b'width', wagtail.wagtailcore.blocks.IntegerBlock(required=True)), (b'height', wagtail.wagtailcore.blocks.IntegerBlock(required=True))]))], blank=True, null=True),
        ),
    ]
