# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 14:18
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20161208_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('doc_with_preview', wagtail.wagtailcore.blocks.StructBlock([(b'preview', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'doc', wagtail.wagtaildocs.blocks.DocumentChooserBlock())])), ('doc_with_preview_row', wagtail.wagtailcore.blocks.StructBlock([(b'first_doc', wagtail.wagtailcore.blocks.StructBlock([(b'preview', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'doc', wagtail.wagtaildocs.blocks.DocumentChooserBlock())])), (b'second_doc', wagtail.wagtailcore.blocks.StructBlock([(b'preview', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'doc', wagtail.wagtaildocs.blocks.DocumentChooserBlock())]))])), ('code', wagtail.wagtailcore.blocks.StructBlock([(b'language', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('python', 'Python'), ('java', 'Java'), ('imagej', 'ImageJ Macro'), ('bash', 'Bash/Shell'), ('html', 'HTML'), ('css', 'CSS'), ('scss', 'SCSS')])), (b'code', wagtail.wagtailcore.blocks.TextBlock())]))], blank=True, null=True),
        ),
    ]
