# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:56
from __future__ import unicode_literals

from django.db import migrations
import nicpages.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('nicpages', '0007_auto_20161201_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nicpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('image_responsive', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock())])), ('doc_with_preview', wagtail.wagtailcore.blocks.StructBlock([(b'preview', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'doc', wagtail.wagtaildocs.blocks.DocumentChooserBlock())])), ('home_video', nicpages.models.HomePageVideoBlock(icon='media')), ('equipment_banner_row', wagtail.wagtailcore.blocks.StructBlock([(b'first_image', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False))])), (b'second_image', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False))]))])), ('google_map', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=True)), (b'street', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=True)), (b'postcode', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=True)), (b'city', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=True)), (b'map_long', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=True)), (b'map_lat', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=True)), (b'map_zoom_level', wagtail.wagtailcore.blocks.CharBlock(default=14, max_length=3, required=True))]))], blank=True, null=True),
        ),
    ]
