# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nicpages', '0018_auto_20161202_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nicpagecarouselitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='nicpagecarouselitem',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='nicpagecarouselitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='nicpagecarouselitem',
            name='page',
        ),
        migrations.DeleteModel(
            name='NicPageCarouselItem',
        ),
    ]
