# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nicpages', '0026_auto_20161202_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revealjspage',
            old_name='slide_deck',
            new_name='body',
        ),
    ]
