# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 16:41
from __future__ import unicode_literals

from django.db import migrations
import nicpages.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('nicpages', '0027_auto_20161202_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revealjspage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False))])), ('transition', nicpages.models.SlideTransitionChoiceBlock()), ('slide_content', wagtail.wagtailcore.blocks.RichTextBlock()), ('sub_slide', wagtail.wagtailcore.blocks.StreamBlock([(b'image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False))])), (b'slide_content', wagtail.wagtailcore.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
