# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('nicpages', '0031_auto_20161205_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revealjspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='RevealJSPage',
        ),
    ]
