# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nicpages', '0039_auto_20170306_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nicpage',
            name='repeat_in_subnav',
        ),
        migrations.RemoveField(
            model_name='nicpage',
            name='repeated_item_text',
        ),
    ]
