# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailimages', '0018_remove_rendition_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('repeat_in_subnav', models.BooleanField(default=False, help_text="If checked, a link to this page will be repeated alongside it's direct children when displaying a sub-navigation for this page.", verbose_name='repeat in sub-navigation')),
                ('repeated_item_text', models.CharField(blank=True, help_text="e.g. 'Section home' or 'Overview'. If left blank, the page title will be used.", max_length=255, verbose_name='repeated item link text')),
                ('body', wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('doc_with_preview', wagtail.core.blocks.StructBlock([(b'preview', wagtail.images.blocks.ImageChooserBlock()), (b'doc', wagtail.documents.blocks.DocumentChooserBlock())])), ('doc_with_preview_row', wagtail.core.blocks.StructBlock([(b'first_doc', wagtail.core.blocks.StructBlock([(b'preview', wagtail.images.blocks.ImageChooserBlock()), (b'doc', wagtail.documents.blocks.DocumentChooserBlock())])), (b'second_doc', wagtail.core.blocks.StructBlock([(b'preview', wagtail.images.blocks.ImageChooserBlock()), (b'doc', wagtail.documents.blocks.DocumentChooserBlock())]))])), ('code', wagtail.core.blocks.StructBlock([(b'language', wagtail.core.blocks.ChoiceBlock(choices=[('python', 'Python'), ('java', 'Java'), ('imagej', 'ImageJ Macro'), ('bash', 'Bash/Shell'), ('html', 'HTML'), ('css', 'CSS'), ('scss', 'SCSS')])), (b'code', wagtail.core.blocks.TextBlock())]))], blank=True, null=True)),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
