# Generated by Django 2.2.6 on 2019-10-18 09:17

from django.db import migrations, models
import django.db.models.deletion
import nic_website_wagtail.wiki.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('repeat_in_subnav', models.BooleanField(default=False, help_text="If checked, a link to this page will be repeated alongside it's direct children when displaying a sub-navigation for this page.", verbose_name='repeat in sub-navigation')),
                ('repeated_item_text', models.CharField(blank=True, help_text="e.g. 'Section home' or 'Overview'. If left blank, the page title will be used.", max_length=255, verbose_name='repeated item link text')),
                ('body', wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('doc_with_preview', wagtail.core.blocks.StructBlock([('preview', wagtail.images.blocks.ImageChooserBlock()), ('doc', wagtail.documents.blocks.DocumentChooserBlock())])), ('doc_with_preview_row', wagtail.core.blocks.StructBlock([('first_doc', wagtail.core.blocks.StructBlock([('preview', wagtail.images.blocks.ImageChooserBlock()), ('doc', wagtail.documents.blocks.DocumentChooserBlock())])), ('second_doc', wagtail.core.blocks.StructBlock([('preview', wagtail.images.blocks.ImageChooserBlock()), ('doc', wagtail.documents.blocks.DocumentChooserBlock())]))])), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('python', 'Python'), ('java', 'Java'), ('imagej', 'ImageJ Macro'), ('bash', 'Bash/Shell'), ('html', 'HTML'), ('css', 'CSS'), ('scss', 'SCSS')])), ('code', wagtail.core.blocks.TextBlock())])), ('video', nic_website_wagtail.wiki.models.VideoBlock(icon='media')), ('OMERO_Dataset', wagtail.core.blocks.StructBlock([('microscope', wagtail.core.blocks.ChoiceBlock(choices=[('a1_inv_confocal', 'A1 Inverted Confocal'), ('a1_up_confocal', 'A1 Upright Confocal'), ('a1r_confocal', 'A1R Confocal'), ('a1r_mp', 'A1R Multi-photon'), ('nsim', 'N-SIM')])), ('thumbnail', nic_website_wagtail.wiki.models.OmeroEmbedBlock(omero_type='thumbnail')), ('gallery', wagtail.core.blocks.PageChooserBlock())])), ('OMERO_Gallery', nic_website_wagtail.wiki.models.OmeroImageListBlock(nic_website_wagtail.wiki.models.OmeroEmbedBlock(label='Image ID')))], blank=True, null=True)),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
