# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 15:09
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks
import nic_website_wagtail.wiki.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('doc_with_preview', wagtail.core.blocks.StructBlock([(b'preview', wagtail.images.blocks.ImageChooserBlock()), (b'doc', wagtail.documents.blocks.DocumentChooserBlock())])), ('doc_with_preview_row', wagtail.core.blocks.StructBlock([(b'first_doc', wagtail.core.blocks.StructBlock([(b'preview', wagtail.images.blocks.ImageChooserBlock()), (b'doc', wagtail.documents.blocks.DocumentChooserBlock())])), (b'second_doc', wagtail.core.blocks.StructBlock([(b'preview', wagtail.images.blocks.ImageChooserBlock()), (b'doc', wagtail.documents.blocks.DocumentChooserBlock())]))])), ('code', wagtail.core.blocks.StructBlock([(b'language', wagtail.core.blocks.ChoiceBlock(choices=[('python', 'Python'), ('java', 'Java'), ('imagej', 'ImageJ Macro'), ('bash', 'Bash/Shell'), ('html', 'HTML'), ('css', 'CSS'), ('scss', 'SCSS')])), (b'code', wagtail.core.blocks.TextBlock())])), ('video', nic_website_wagtail.wiki.models.VideoBlock(icon='media'))], blank=True, null=True),
        ),
    ]
