# Generated by Django 2.2.6 on 2019-11-05 13:47

from django.db import migrations
import nic_website_wagtail.home.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191105_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('media', nic_website_wagtail.home.models.HomePageVideoBlock(icon='media'))]),
        ),
    ]
