# Generated by Django 2.2.6 on 2019-11-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191105_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_subtitle',
        ),
    ]
