# Generated by Django 2.2.6 on 2019-11-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepagegalleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_image',
        ),
    ]
