# Generated by Django 2.2.6 on 2019-11-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_supplierimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='formatted_address',
            field=models.CharField(default='Newcomen St, London, UK', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='latlng_address',
            field=models.CharField(default='51.503292, -0.089385', max_length=255),
            preserve_default=False,
        ),
    ]
