# Generated by Django 2.2.6 on 2019-11-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191108_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='latlng_address',
        ),
    ]
