# Generated by Django 2.2.6 on 2019-11-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_homepage_latlng_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='formatted_address',
        ),
    ]
