# Generated by Django 2.2.6 on 2019-11-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_homepage_formatted_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='map_lat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='map_long',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='map_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='map_zoom_level',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='postcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
