# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('slide_deck', '0002_slidedeck_slidedeckslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidedeckslide',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
