# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 10:34
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('slide_deck', '0004_auto_20170314_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidedeck',
            name='carousel',
            field=wagtail.wagtailcore.fields.StreamField([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'quotation', wagtail.wagtailcore.blocks.StructBlock([('text', wagtail.wagtailcore.blocks.TextBlock()), ('author', wagtail.wagtailcore.blocks.CharBlock())])), (b'video', wagtail.wagtailembeds.blocks.EmbedBlock())], default=None),
            preserve_default=False,
        ),
    ]
