# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slide_deck', '0005_slidedeck_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidedeck',
            name='carousel',
        ),
    ]
