# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('slide_deck', '0007_slidedeckslide_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', wagtail.wagtailcore.fields.RichTextField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='slidedeckslide',
            name='content',
        ),
        migrations.RemoveField(
            model_name='slidedeckslide',
            name='id',
        ),
        migrations.RemoveField(
            model_name='slidedeckslide',
            name='image',
        ),
        migrations.AddField(
            model_name='slidedeckslide',
            name='slidefields_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='slide_deck.SlideFields'),
            preserve_default=False,
        ),
    ]
