# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('slide_deck', '0008_auto_20170315_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidedeckslide',
            name='slidefields_ptr',
        ),
        migrations.AddField(
            model_name='slidedeckslide',
            name='content',
            field=wagtail.wagtailcore.fields.RichTextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slidedeckslide',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slidedeckslide',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='slidedeckslide',
            name='subslide_content',
            field=wagtail.wagtailcore.fields.RichTextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slidedeckslide',
            name='subslide_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
