# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailmenus', '0021_auto_20170106_2352'),
        ('slide_deck', '0009_auto_20170315_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidedeck',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='slidedeckslide',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slidedeckslide',
            name='slide',
        ),
        migrations.RemoveField(
            model_name='slidedeckslide',
            name='subslide_image',
        ),
        migrations.RemoveField(
            model_name='slidefields',
            name='image',
        ),
        migrations.RenameField(
            model_name='slidedeckpage',
            old_name='body',
            new_name='deck',
        ),
        migrations.DeleteModel(
            name='SlideDeck',
        ),
        migrations.DeleteModel(
            name='SlideDeckSlide',
        ),
        migrations.DeleteModel(
            name='SlideFields',
        ),
    ]
