# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 15:21
from __future__ import unicode_literals

from django.db import migrations
import slide_deck.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('slide_deck', '0014_auto_20170315_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidedeckpage',
            name='deck',
            field=wagtail.wagtailcore.fields.StreamField([('slide', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'transition', slide_deck.models.SlideTransitionChoiceBlock()), (b'slide_content', wagtail.wagtailcore.blocks.RichTextBlock()), (b'sub_slide', wagtail.wagtailcore.blocks.StreamBlock([(b'subslide_image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False))])), (b'subslide_content', wagtail.wagtailcore.blocks.RichTextBlock())]))]))], blank=True, null=True),
        ),
    ]
