# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 14:37
from __future__ import unicode_literals

import blog.models
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogindexpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('h1', wagtail.wagtailcore.blocks.CharBlock(icon='title')), ('h2', wagtail.wagtailcore.blocks.CharBlock(icon='title')), ('h3', wagtail.wagtailcore.blocks.CharBlock(icon='title')), ('h4', wagtail.wagtailcore.blocks.CharBlock(icon='title')), ('h5', wagtail.wagtailcore.blocks.CharBlock(icon='title')), ('centre_heading', blog.models.CentreAlignHeadingBlock()), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('video', blog.models.VideoBlock(icon='media')), ('home_video', blog.models.VideoBlock(icon='media'))], blank=True, null=True),
        ),
    ]
