# Generated by Django 2.2.6 on 2019-10-18 09:17

from django.db import migrations, models
import django.db.models.deletion
import nic_website_wagtail.slide_deck.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideDeckPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('deck', wagtail.core.fields.StreamField([('slide', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('transition', nic_website_wagtail.slide_deck.models.SlideTransitionChoiceBlock()), ('slide_content', wagtail.core.blocks.RichTextBlock()), ('sub_slide', wagtail.core.blocks.StreamBlock([('subslide_image', wagtail.images.blocks.ImageChooserBlock()), ('subslide_content', wagtail.core.blocks.RichTextBlock())]))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
